services:
  blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dev
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./
          target: /app/
          action: sync
          ignore:
            - node_modules
            - .next
            - Dockerfile
            - docker-compose.yml
    command: ["npm", "run", "dev"]
    # volumes:
    #   - .:/app
