services:
  blog:
    build:
      context: .
      dockerfile: ./blog/Dockerfile
    image: dev
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - path: ./blog/package.json
          action: rebuild
        - path: ./blog/Dockerfile
          action: rebuild
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./blog
          target: /app/blog
          action: sync
          ignore:
            - node_modules
            - .next
        - path: ./content
          target: /app/content
          action: sync
    command: ["sh", "-c", "ls && cd blog && npm run dev"]
    # volumes:
    #   - .:/app
